services:
  op-init:
    image: alpine:latest
    command:
      - sh
      - -c
      - |
        set -e

        # Create config directory
        mkdir -p /config

        # Generate JWT secret if it doesn't exist
        if [ ! -f '/jwt/jwt' ]; then
          echo 'Generating JWT secret'
          mkdir -p /jwt
          # Generate a 32-byte random hex string for JWT secret
          apk add --no-cache openssl
          openssl rand -hex 32 > /jwt/jwt
          chmod 666 /jwt/jwt
          echo 'JWT secret generated successfully'
        else
          echo 'JWT secret already exists, skipping generation'
        fi
    volumes:
      - op_node_data:/op-node
      - jwt_shared:/jwt

  op-geth-init:
    image: golemnetwork/golembase-l3-op-geth:v1.101603.3-8.6-hoodi-kaolin-cfdf2cd9
    depends_on:
      op-init:
        condition: service_completed_successfully
    entrypoint: []
    command:
      - /bin/sh
      - -c
      - |
        set -e
        if [ ! -f '/geth/geth' ]; then
          echo 'Initializing geth data directory with genesis block...'

          # Use genesis file from op-init
          if ! geth init --state.scheme=hash --datadir='/geth' '/genesis.json'; then
            echo 'ERROR: Failed to initialize geth with genesis block'
            exit 1
          fi
          echo 'Geth initialized successfully with genesis block'
        else
          echo 'Geth data directory already initialized, skipping initialization'
        fi
    volumes:
      - op_geth_data:/geth

  op-geth:
    image: golemnetwork/golembase-l3-op-geth:v1.101603.3-8.6-hoodi-kaolin-cfdf2cd9
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-geth-init:
        condition: service_completed_successfully
    command:
      - --networkid=60138453025
      - --datadir=/geth
      - --http
      - --http.corsdomain=*
      - --http.vhosts=*
      - --http.addr=0.0.0.0
      - --http.port=8545
      - --http.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
      - --ws
      - --ws.addr=0.0.0.0
      - --ws.port=8546
      - --ws.origins=*
      - --ws.api=admin,debug,eth,txpool,net,engine,web3,golembase,txpool
      - --syncmode=full
      - --gcmode=archive
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.port=8551
      - --authrpc.jwtsecret=/jwt/jwt
      - --usb=false
      - --state.scheme=hash
      - --nat=none
      - --bootnodes=enode://8613436d093d81f22c51dccb77ad3e9824a1d10dc5019ee32d79558cc853a4d47405d05b6b664a39522b8de55ccfc16a5d1c1d14b9d404dd535b32df1d7a2aa4@57.130.8.174:46072,enode://3becdeed26aa1c159f7e39b61d7ada5273b16441c69578f3d56c2433ca7aa1d8c1dee16cc2f03e704babb0fe5075d95760d41adbe551cee2dea37673cb499308@57.130.8.167:46074,enode://cd404ef747f135f2fe3d6e4d0399bcfa57c402d5888e9c85c28bf30437e14246e373e9782bc9042f7b92f890ad19bf48b760e354b40d2d890a418f10d39d8c1a@57.130.8.112:46076,enode://43fa83fde8c9b2ddd771898cd0d4048a3c46c18213c9bd90de96567345778788a6ee3f527bfd633c1fd62c58f4720da8cd22ee7893ed0db9e64a09483336890d@57.130.9.134:46078,enode://b5550d7f4a7fbf6114ec3074fa5a8b4a32692f3ac273a3039dcb2f77cc8b473ca5992e902676801be50d20815d911caf79ae345fd09d5e8993cc6e27d4dfacf0@57.130.8.252:46080
      - --txpool.disable.non.golembase.transactions=true
    ports:
      - 127.0.0.1:8545:8545
    volumes:
      - op_geth_data:/geth
      - jwt_shared:/jwt

  op-node:
    image: golemnetwork/golembase-l3-op-node:v1.16.2-hoodi-kaolin-5723047a
    restart: unless-stopped
    stop_grace_period: 5m
    depends_on:
      op-init:
        condition: service_completed_successfully
      op-geth:
        condition: service_started
    command:
      - op-node
      - --l1=https://l2.hoodi.arkiv.network/rpc
      - --l1.beacon.ignore=true
      - --l1.rpckind=standard
      - --l1.trustrpc
      - --l2=http://op-geth:8551
      - --l2.enginekind=geth
      - --l2.jwt-secret=/jwt/jwt
      - --rpc.addr=0.0.0.0
      - --rpc.port=9545
      - --p2p.nat=true
      - --p2p.ban.peers=false
      - --p2p.bootnodes=enr:-KG4QBpPZq2F_5xvGZ05L6RKlDzz3hDmguYlrAT0mJiQuTF2W8QW19nV_rR-SN2IsqFoCcLQQ8Jy40FWla5XpwK9CtCGAZu25omtgmlkgnY0gmlwhDmCCK6Hb3BzdGFja4eh8J-E4AEAiXNlY3AyNTZrMaEC_357nXnVdKQv_sLT_2DQBxuepySmsvoGa5xdrDEeR4qDdGNwgrP5g3VkcIKz-Q,enr:-KG4QD02ppZdBWtgVB-gAvP4h85NpgDaNFwodpvXq7tuh16vQ4XRzo3XotaMfJIQu51miBx8kb6iaGBoK8fZDL4lSuqGAZu25pSbgmlkgnY0gmlwhDmCCKeHb3BzdGFja4eh8J-E4AEAiXNlY3AyNTZrMaEDIGnW5-e1f2YcnWivQLfVM0O53iZG8u0f2Fl5lkb78aGDdGNwgrP7g3VkcIKz-w,enr:-KG4QGA4LRm0RWi0nfNEsD3P_O7ewMAqeeU3fq_ekJOg4PSTCJCwi5ZxbSfJ2WCGqomUrJALvYnBmTSt6pHmAhb3yDuGAZu25od9gmlkgnY0gmlwhDmCCHCHb3BzdGFja4eh8J-E4AEAiXNlY3AyNTZrMaECpOS3b0ETa5D6Iyp96z4FLcPgfagp8-IZzC2UMLLfGf2DdGNwgrP9g3VkcIKz_Q,enr:-KG4QK15i5-ZWoVD6J8POJYI7KRsCPVOSul0Ga6qEs1M-OYMA3AonpHe-5n5TC1GTXYujE4XyoDGSiV5dDxzWN-kXH6GAZu25pf4gmlkgnY0gmlwhDmCCYaHb3BzdGFja4eh8J-E4AEAiXNlY3AyNTZrMaEDraEGOYS1EfgA6cnJohRZNB3hLoflKO1ePKhUw2TgHDiDdGNwgrP_g3VkcIKz_w,enr:-KG4QEX_q9n_oRzAfGoDnAuS2mKphqrTE1M-3P_XTCteC1i3P6rpzujMr9PB3xM3vwmfEdHw1Nt6kx2dbUyg50-PuemGAZu25oi7gmlkgnY0gmlwhDmCCPyHb3BzdGFja4eh8J-E4AEAiXNlY3AyNTZrMaEDOvWNvkZsa1cOmrct-c6AAmnpome8_Fi4XwWj0c-p_xSDdGNwgrQBg3VkcIK0AQ
      - --p2p.listen.tcp=9222
      - --p2p.listen.udp=9222
      - --metrics.enabled
      - --metrics.addr=0.0.0.0
      - --metrics.port=7300
      - --syncmode=execution-layer
      - --rollup.config=/rollup.json
      - --rollup.l1-chain-config=/genesis.json
      - --log.level=info
    volumes:
      - jwt_shared:/jwt
      - op_node_data:/op-node

volumes:
  op_geth_data:
  op_node_data:
  jwt_shared:
